# G2

Demonstration of how to use the `clifford` module for two dimension space, aka $G^2$

## Create the algebra and basis 

In [1]:
from clifford import *

pretty(precision=2)    # sets display precision 

layout, blades = Cl(2) # creates a 2-dimensional clifford algebra

In [2]:
blades

{'e0': (1.0^e0), 'e01': (1.0^e01), 'e1': (1.0^e1)}

In [3]:
# define some variables for blades
e0 = blades['e0']
e1 = blades['e1']
e01 = blades['e01']

## Basics 

In [4]:
e0*e1 # geometric product

(1.0^e01)

In [5]:
e0^e1 # outer product

(1.0^e01)

In [6]:
e0|e1 # inner product

0

**NOTE**: Make sure you use parenthesis with wedge and addition/subtraction, because the operators `+` and `-` have higher precidence than `^`. For example

In [7]:
e0^e1 + e0^e1 # fail

0

In [8]:
(e0^e1) + (e0^e1) # success

(2.0^e01)

## Create Random Data 

In [9]:
# create a random vector 
layout.randomV()

-(1.75^e0) - (1.91^e1)

In [10]:
# create a random Rotor 
layout.randomRotor()

0.66 + (0.76^e01)

In [11]:
# create a random Spinor 
rand()^layout.randomRotor()

-0.07 + (0.03^e01)

In [12]:
# create a list of random vectors
r = layout.randomV(10)
r

[(0.77^e0) + (1.81^e1),
 -(1.01^e0) + (1.34^e1),
 (0.56^e0) - (0.08^e1),
 -(1.92^e0) + (2.0^e1),
 (1.78^e0) - (0.7^e1),
 -(0.19^e0) + (1.57^e1),
 -(1.78^e0) - (0.66^e1),
 (0.32^e0) + (1.04^e1),
 -(1.75^e0) + (1.51^e1),
 (1.71^e0) - (0.45^e1)]

## Conversion between $G^2$ and Complex Numbers

It is sometimes neccesary to convert complex numbers to objects in $G^2$. How this is mapped is up to you, but here are some options

In [13]:
def c2v(c):
    '''
    convert a complex number to a 2D vector
    '''
    return (c.real^e0) + (c.imag^e1)

In [14]:
c2v(1+1j)

(1.0^e0) + (1.0^e1)

In [15]:
def v2c(v):
    '''
    convert a  2D vector to a complex number
    '''
    return float(v|e0) + float(v|e1)*1j

In [16]:
v2c(e0+e1)

(1+1j)

In [17]:
def c2S(c):
    '''
    convert a complex number to a 2D Spinor
    '''
    return (c.real) + (c.imag^e01)

In [18]:
c2S(exp(pi/4 *1j))

array([ 0.70710678,  0.70710678,  0.70710678,  1.41421356])

In [19]:
x= e01._newMV()
x[()]=float64(3)
type(x)
x.value +e01.value

array([ 3.,  0.,  0.,  1.])

In [21]:
R = exp(blades['e01'])
e0 = blades['e0']
R*e0*~R

TypeError: ufunc 'invert' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [25]:
e**(e01)

0.54 + (0.84^e01)

In [27]:
log(e01)

-c:1: RuntimeWarning: divide by zero encountered in log


array([-inf, -inf, -inf,   0.])

In [38]:
other = e01._checkOther(float64(4))[0]
e01._newMV(other.value+e01.value)

4.0 + (1.0^e01)

In [66]:
import clifford as cf
layout, blades = cf.Cl(2) 

e0= blades['e0']
e0.__radd__(float64(4))

4.0 + (1.0^e0)

In [67]:
e0.__add__(float64(4))

4.0 + (1.0^e0)

In [69]:
float64(4)+e0

array([ 4.,  5.,  4.,  4.])

In [44]:
float64??

In [45]:
exp??

In [55]:
class Me(object):
    def __init__(self,val):
        self.value = ones(3)
        self.value *=val

In [57]:
me = Me(3)

me

In [59]:
float64(4)+me

TypeError: unsupported operand type(s) for +: 'float' and 'Me'